name: Build conda
inputs:
  label:
    description: "Label"
    default: ""
    required: false
  cuda:
    description: "cuda"
    default: ""
    required: false
  raft:
    description: "raft"
    default: ""
    required: false
  cuda_archs:
    description: "cuda_archs"
    default: ""
    required: false
  compiler_version:
    description: "compiler_version"
    default: ""
    required: false
runs:
  using: composite
  steps:
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3.0.3
      with:
        python-version: '3.11'
        miniconda-version:  latest
    - name: Install conda build tools
      shell: bash
      run: |
        # conda config --set solver libmamba
        # conda config --set verbosity 3
        conda update -y -q conda
        conda install -y -q conda-build
    - name: Enable anaconda uploads
      if: inputs.label != ''
      shell: bash
      run: |
        conda install -y -q anaconda-client
        conda config --set anaconda_upload yes
    - name: Conda build (CPU)
      if: inputs.label == '' && inputs.cuda == ''
      shell: bash
      working-directory: conda
      run: |
        conda build faiss --python 3.11 -c pytorch
    - name: Conda build (CPU) w/ anaconda upload
      if: inputs.label != '' && inputs.cuda == ''
      shell: bash
      working-directory: conda
      run: |
        conda build faiss --user pytorch --label <<parameters.label>> -c pytorch
    - name: Conda build (GPU)
      if: inputs.label == '' && inputs.cuda != '' && inputs.raft == ''
      shell: bash
      working-directory: conda
      run: |
        conda build faiss-gpu --variants '{ "cudatoolkit": "<<parameters.cuda>>", "c_compiler_version": "<<parameters.compiler_version>>", "cxx_compiler_version": "<<parameters.compiler_version>>" }' \
            -c pytorch -c nvidia/label/cuda-<<parameters.cuda>> -c nvidia
    - name: Conda build (GPU) w/ anaconda upload
      if: inputs.label != '' && inputs.cuda != '' && inputs.raft == ''
      shell: bash
      working-directory: conda
      run: |
        conda build faiss-gpu --variants '{ "cudatoolkit": "<<parameters.cuda>>", "c_compiler_version": "<<parameters.compiler_version>>", "cxx_compiler_version": "<<parameters.compiler_version>>" }' \
            --user pytorch --label <<parameters.label>> -c pytorch -c nvidia/label/cuda-<<parameters.cuda>> -c nvidia
    - name: Conda build (GPU w/ RAFT)
      if: inputs.label == '' && inputs.cuda != '' && inputs.raft != ''
      shell: bash
      working-directory: conda
      run: |
        conda build faiss-gpu-raft --variants '{ "cudatoolkit": "<<parameters.cuda>>", "c_compiler_version": "<<parameters.compiler_version>>", "cxx_compiler_version": "<<parameters.compiler_version>>" }' \
            -c pytorch -c nvidia/label/cuda-<<parameters.cuda>> -c nvidia -c rapidsai -c conda-forge
    - name: Conda build (GPU w/ RAFT) w/ anaconda upload
      if: inputs.label != '' && inputs.cuda != '' && inputs.raft != ''
      shell: bash
      working-directory: conda
      run: |
        conda build faiss-gpu-raft --variants '{ "cudatoolkit": "<<parameters.cuda>>", "c_compiler_version": "<<parameters.compiler_version>>", "cxx_compiler_version": "<<parameters.compiler_version>>" }' \
            --user pytorch --label <<parameters.label>> -c pytorch -c nvidia/label/cuda-<<parameters.cuda>> -c nvidia -c rapidsai -c conda-forge